### ISSUE TITLE
Baggy Soap Company typo

### ISSUE THREAD

**Issue by mitchk1609** [MitchellSoftTechnology/mitchellsoft#7]
Just a small issue - it should be "The Baggy Soap Company" in the description shown below, instead of "The **b**agg**ie** **s**oap **c**ompany"

![image](https://user-images.githubusercontent.com/3582580/109404057-3cdbfe00-795a-11eb-9e47-257886450c13.png)

**Comment by jonathanw82** [comment]
This is now corrected
